name: CI/CD - EKS Deployment

on:
  push:
    branches:
      - cicd

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  FRONTEND_IMAGE: password-frontend
  BACKEND_IMAGE: password-backend
  CLUSTER_NAME: my-cluster
  AWS_REGION: eu-west-2
  NAMESPACE: password

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.NEW_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Version Tag
        id: tag
        run: |
          NEW_TAG=v${{ github.run_number }}
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ steps.tag.outputs.NEW_TAG }} ./frontend
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ steps.tag.outputs.NEW_TAG }}

      - name: Build & Push Backend
        run: |
          docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ steps.tag.outputs.NEW_TAG }} ./backend
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ steps.tag.outputs.NEW_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/sc.yaml
          kubectl apply -f k8s/headless.yaml
          kubectl apply -f k8s/mongo-statefulset.yaml
          kubectl apply -f k8s/job.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Update Images (Rolling Update)
        run: |
          kubectl set image deployment/frontend frontend=$DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ needs.build-and-push.outputs.tag }} -n $NAMESPACE
          kubectl set image deployment/backend backend=$DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ needs.build-and-push.outputs.tag }} -n $NAMESPACE

      - name: Verify
        run: kubectl get all -n $NAMESPACE